//user
export const SET_USER_DATA = 'SET_USER_DATA';

//rides
export const SET_RIDES = 'SET_RIDES';
export const SET_USER_RIDES = 'SET_USER_RIDES';
export const SET_SINGLE_RIDE = 'SET_SINGLE_RIDE';
export const SET_RIDE_REQUESTS = 'SET_RIDE_REQUESTS';
export const SET_RIDE_PASSENGERS = 'SET_RIDE_PASSENGERS';
export const CLEAR_RIDE_REQUESTS = 'CLEAR_RIDE_REQUESTS';
